version: "3.9"
services:
  run:
    build:
      context: .         # ← this tells Compose “use the Dockerfile here”
    volumes:
      - .:/app
    command: python3 main.py

  test:
    build:
      context: .
    volumes:
      - .:/app
    command: python3 -m pytest
